### ISSUE TITLE
First selection in dropdown ignored

### ISSUE THREAD

**Issue by ghost** [dillonjohnbrown/the-drugulator#1]
After loading the site, regardless which drug is selected in the drop-down, the selection is set to `2c-x`. Any selection after that works fine. Happens in Firefox 86.0.

**Comment by dillonjohnbrown** [comment]
Thank you for finding this bug! I can see it on Firefox too, 86.0.1 on macOS. I'll see if I can figure it out.

**Comment by dillonjohnbrown** [comment]
If anyone reading this is well-versed in JavaScript and wants to help I would happily accept some assistance.
