### ISSUE TITLE
Inappropriate safety claim

### ISSUE THREAD

**Issue by postcasio** [dillonjohnbrown/the-drugulator#2]
You should avoid claiming that this project allows you to "safely" combine recreational drugs. You do have some disclaimers on here but I think it's inappropriate to have that tagline.

Some of these drugs have the potential to kill, and you can't really make the determination that these combinations are ever safe.

**Comment by dillonjohnbrown** [comment]
Thank you for the suggestion. I agree the word "safely" might not be my best word choice, especially when dealing in this area.

As for your other point regarding some drugs potential to kill, I subscribe to the "dose makes the poison" school of thought. _All of these drugs_ have the potential to kill if your dose is too much. All of them also have less than lethal doses for all other kinds of purposes.

I've replaced all references implying this tool has anything to do with safety. It really is for education, anyway.
